
name: Java CI with Gradle
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "spring-boot-application-packages"
  EB_APLICATION_NAME        : "MyApp"
  EB_ENVIORNMENT_NAME       : "Myapp-env"
  AWS_REGION_NAME           : "eu-north-1"
  

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: make gradlew exe
      run: chmod +x gradlew
    - name: test and packege with gradle
      run: ./gradlew bootJar
    - name: our jar
      run: |
       cd build/libs
       ls

   
    
#   test:
#     runs-on: ubuntu-latest
#     needs: [build]
    
    
      
