
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
#     - name: make gradlew exe
#       run: chmod +x gradlew
    - name: test and packege with gradle
      run: ./gradlew build
   
    
#   test:
#     runs-on: ubuntu-latest
#     needs: [build]
    
    
      
