
name: CI-CD-pipeline-build-demploy-to-AWS
env: 
  EB_PACKAGE_S3_BUCKET_NAME : "spring-boot-application-packages"
  EB_APLICATION_NAME        : "MyApp"
  EB_ENVIORNMENT_NAME       : "Myapp-env"
  AWS_REGION_NAME           : "eu-north-1"
  DEPLOY_PACKAGE_PATH       : "/home/runner/work/github-actions-cicd-to-aws/github-actions-cicd-to-aws/build/libs/github-actions-cicd-to-aws-0.0.1-SNAPSHOT.jar"
  DEPLOY_PACKAGE_NAME       : "github-actions-cicd-to-aws-0.0.1-SNAPSHOT.jar"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci-part:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: make gradlew exe
      run: chmod +x gradlew
    - name: test and packege with gradle
      run: ./gradlew bootJar
    - name: Config AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
        aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
        aws-region            : ${{ env.AWS_REGION_NAME }}
    - name: Copy deplotment package into S3 bucket
      run : aws s3 cp ${{ env.DEPLOY_PACKAGE_PATH }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME}}/
    - name: print massage about CI happy end
      run: echo "CI pipline finished successfuly"

   
    
  cd-part:
    runs-on: ubuntu-latest
    needs: [ci-part]
    
    steps:
      - name: Config AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id     : ${{ secrets.MY_AWS_ACCESS_KEY }}
          aws-secret-access-key : ${{ secrets.MY_AWS_SECRET_KEY }}
          aws-region            : ${{ env.AWS_REGION_NAME }}
      - name: Create new ElasticBeanstalk application version 
        run: |
          aws elasticbeanstalk create-application-version \
          --application-name ${{ env.EB_APLICATION_NAME }} \
          --source-bundle S3Bucket=$"{{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{ env.DEPLOY_PACKAGE_NAME }}" \
          --version-label "Ver-${{ github.sha }}" \ 
          --description "CommitSHA-${{ github.sha }}"
      - name : Deploy new ElasticBeanstalk application version
        run: aws elasticbeanstalk update-environment \
             --environment-name ${{ env.EB_ENVIORNMENT_NAME }} \
             --version-label "Ver-${{ github.sha }}"
      - name: print massage about CD happy end
        run: echo "CD pipline finished successfuly"
    
      
