
name: Java CI with Gradle

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: current directory
      run: pwd
    - name: show current directory
      run: ls -la 
    - name: test with gradle
      run: gradlew test
    
#   test:
#     runs-on: ubuntu-latest
#     needs: [build]
    
    
      
